### ISSUE TITLE
FSP support

### ISSUE THREAD

**Issue by elifoster** [mallrat208/ExpandedArmory#5]
You should totally add support for Brass and Gilded weapons.

**Comment by mallrat208** [comment]
Funny story, someone mentioned that eariler in IRC, go figure

**Comment by mallrat208** [comment]
![Brass Powah](http://puu.sh/mB0r5/b6c518c140.png)

Good news: Expanded Armory is soon to support Brass and Gilded Iron Weaponry if FSP is installed. 

Bad News: Brass Weaponry are pretty damn ugly.

**Comment by elifoster** [comment]
I disagree, actually.
